"use client";

import Image from "next/image";
import {
  Fragment,
  useCallback,
  useEffect,
  useRef,
  useState,
  type ReactNode,
} from "react";
import { didWebToDidJsonHttpsUrl, rewriteTabulasHttpsUrl } from "@/lib/did-web";
import { verifyDemoCredential } from "@/lib/demo-verify";

const DISCLOSURE_BODY = `The product data shown on this page comes from Wienerberger's published Environmental Product Declaration (EPD-IES-0024019), verified by Dr.-Ing. Nikolay Minkov of greentability Ltd. and registered with EPD International AB. The cryptographic signatures shown here were generated by Tabulas for demonstration purposes. In a live deployment, each party — Wienerberger, greentability, and the installing contractor — would hold their own keys and issue their own signatures. No party shown here has endorsed this demonstration.`;

const WHY_SIGNED_CLAIM_INTRO =
  "A signed claim is a JSON file with a tamper-proof seal. The seal is made once, by whoever's making the claim. After that, anyone in the world can check the seal without contacting the original sender. If the seal checks out, two things are true: the claim was really made by the party whose seal it is, and not one character has been changed since. The seal doesn't prove the claim is true — that's what independent verifiers are for, and they get their own seal too. What it proves is that the trail of who said what, and when, can be followed and trusted without depending on any single platform staying online. That's why your EPD becomes durable. Not because we host it — because the seal is yours, and it travels with the data.";

const MATERIAL_DID =
  "did:web:tabulas.eu:materials:wienerberger:porotherm-25-nf";

/** UNE EN 15804:2012+A2:2020 — EPD core rules for construction products (external store listing). */
const EN_15804_CORE_RULES_URL =
  "https://www.en-standard.eu/une-en-15804-2012-a2-2020-sustainability-of-construction-works-environmental-product-declarations-core-rules-for-the-product-category-of-construction-products/";

const CREDENTIAL_PATHS = {
  product:
    "/credentials/wienerberger/porotherm-25-nf/product-declaration.json",
  epd: "/credentials/wienerberger/porotherm-25-nf/epd.json",
  verification:
    "/credentials/wienerberger/porotherm-25-nf/verification.json",
  installation:
    "/credentials/bouwwerken-vandevelde/sint-andries-2026/porotherm-25-nf-batch-001.json",
} as const;

type CredentialKey = keyof typeof CREDENTIAL_PATHS;

/** Last cryptographic verification outcome per credential (hero + table). */
type CredentialVerifyStamp = "idle" | "running" | "ok" | "fail";

const CARDS: {
  key: CredentialKey;
  title: string;
  issuerLine: string;
  quote: string;
  dateLabel: string;
}[] = [
  {
    key: "product",
    title: "Product declaration",
    issuerLine: "Issued by Wienerberger EOOD",
    quote:
      "This material is Porotherm 25 N+F, manufactured in Lukovit.",
    dateLabel: "Valid from 17 June 2025",
  },
  {
    key: "epd",
    title: "Environmental declaration",
    issuerLine: "Issued by Wienerberger EOOD",
    quote:
      "Global warming potential is 182 kg CO₂ eq per ton, cradle to gate, declared 2025.",
    dateLabel: "Valid from 17 June 2025",
  },
  {
    key: "verification",
    title: "Third-party verification",
    issuerLine: "Issued by greentability Ltd.",
    quote:
      "I verified Wienerberger's declaration on behalf of EPD International AB.",
    dateLabel: "Valid from 17 June 2025",
  },
  {
    key: "installation",
    title: "Installation record",
    issuerLine: "Issued by Bouwwerken Vandevelde BV",
    quote:
      "We installed 2,400 kg of this material in Sint-Andries, Brugge, on March 15, 2026.",
    dateLabel: "Valid from 15 March 2026",
  },
];

const PASSPORT_CLAIM_LABEL: Record<CredentialKey, string> = {
  product: "Product",
  epd: "EPD",
  verification: "Verifier",
  installation: "Install",
};

function verifyStampLabel(stamp: CredentialVerifyStamp | undefined): string {
  switch (stamp) {
    case "ok":
      return "Verified";
    case "fail":
      return "Failed";
    case "running":
      return "Checking…";
    default:
      return "Not checked";
  }
}

function verifyStampChipClass(stamp: CredentialVerifyStamp | undefined): string {
  const base =
    "inline-flex min-w-[5.75rem] max-w-[9rem] flex-col rounded-lg border px-2.5 py-1.5 text-left transition-colors sm:min-w-[6.5rem] sm:max-w-none";
  switch (stamp) {
    case "ok":
      return `${base} border-emerald-300 bg-emerald-50 text-emerald-900 dark:border-emerald-700 dark:bg-emerald-950/50 dark:text-emerald-100`;
    case "fail":
      return `${base} border-red-300 bg-red-50 text-red-900 dark:border-red-800 dark:bg-red-950/40 dark:text-red-100`;
    case "running":
      return `${base} border-amber-300 bg-amber-50 text-amber-950 dark:border-amber-700 dark:bg-amber-950/30 dark:text-amber-100`;
    default:
      return `${base} border-zinc-200 bg-white text-zinc-600 hover:bg-zinc-50 dark:border-zinc-600 dark:bg-zinc-900 dark:text-zinc-300 dark:hover:bg-zinc-800/80`;
  }
}

function verifyStampGlyph(stamp: CredentialVerifyStamp | undefined): string {
  switch (stamp) {
    case "ok":
      return "✓";
    case "fail":
      return "✗";
    case "running":
      return "…";
    default:
      return "○";
  }
}

const VERIFY_STEPS = [
  "Fetching VC",
  "Resolving issuer DID",
  "Loading public key",
  "Canonicalizing claim",
  "Verifying signature",
] as const;

function resolutionOriginStatic(): string {
  const fromEnv = process.env.NEXT_PUBLIC_DID_RESOLUTION_ORIGIN?.trim();
  if (fromEnv) {
    return fromEnv.replace(/\/$/, "");
  }
  return "https://tabulas.eu";
}

function useResolutionOrigin(): string {
  const [origin, setOrigin] = useState(resolutionOriginStatic);
  useEffect(() => {
    if (!process.env.NEXT_PUBLIC_DID_RESOLUTION_ORIGIN?.trim()) {
      // Client-only: rewrite tabulas.eu URLs to the actual host (see docs).
      // eslint-disable-next-line react-hooks/set-state-in-effect -- sync browser origin once after mount
      setOrigin(window.location.origin);
    }
  }, []);
  return origin;
}

function DisclosureCallout({
  id,
  expanded,
  onToggle,
}: {
  id: string;
  expanded: boolean;
  onToggle: () => void;
}) {
  return (
    <aside
      id={id}
      role="note"
      aria-label="Demonstration disclosure"
      className="rounded-lg border-2 border-amber-600/80 bg-amber-50 p-4 text-sm leading-relaxed text-zinc-900 shadow-sm dark:border-amber-500 dark:bg-amber-950/40 dark:text-zinc-100"
    >
      <button
        type="button"
        className="flex w-full items-start justify-between gap-3 rounded-md text-left outline-none ring-amber-700/40 focus-visible:ring-2 dark:ring-amber-400/40"
        aria-expanded={expanded}
        onClick={onToggle}
      >
        <span className="font-semibold text-amber-950 dark:text-amber-100">
          About this demonstration
        </span>
        <span className="shrink-0 text-amber-800/80 tabular-nums dark:text-amber-200/90" aria-hidden>
          {expanded ? "▼" : "▶"}
        </span>
      </button>
      {expanded ? <p className="mt-3">{DISCLOSURE_BODY}</p> : null}
    </aside>
  );
}

function resolutionBaseAtRuntime(originState: string): string {
  const env = process.env.NEXT_PUBLIC_DID_RESOLUTION_ORIGIN?.trim();
  if (env) {
    return env.replace(/\/$/, "");
  }
  if (typeof window !== "undefined") {
    return window.location.origin;
  }
  return originState.replace(/\/$/, "");
}

export function DemoDidClient() {
  const [disclosureTopOpen, setDisclosureTopOpen] = useState(false);
  const [disclosureFooterOpen, setDisclosureFooterOpen] = useState(false);
  const [claimNarrativeOpen, setClaimNarrativeOpen] = useState<
    Partial<Record<CredentialKey, boolean>>
  >({});
  const [claimJsonOpen, setClaimJsonOpen] = useState<
    Partial<Record<CredentialKey, boolean>>
  >({});

  const [elementExpanded, setElementExpanded] = useState(false);
  const [identityExpanded, setIdentityExpanded] = useState(false);

  const [didDocOpen, setDidDocOpen] = useState(false);
  const [didDocJson, setDidDocJson] = useState<string | null>(null);
  const [didDocError, setDidDocError] = useState<string | null>(null);
  const [didResolveBusy, setDidResolveBusy] = useState(false);
  /** Where the resolved DID JSON is shown (header Resolve scrolls here). */
  const identitySectionRef = useRef<HTMLElement>(null);

  const [credentialJson, setCredentialJson] = useState<
    Partial<Record<CredentialKey, string>>
  >({});

  const [verifyPanelKey, setVerifyPanelKey] = useState<CredentialKey | null>(
    null,
  );
  /** Which verification line is active during the paced animation; null during crypto work */
  const [highlightLine, setHighlightLine] = useState<number | null>(null);
  const [verifySettled, setVerifySettled] = useState(false);
  const [verifyAnimating, setVerifyAnimating] = useState(false);
  const [finalVerified, setFinalVerified] = useState<boolean | null>(null);
  const [verifyError, setVerifyError] = useState<string | null>(null);
  const [credentialVerifyStamp, setCredentialVerifyStamp] = useState<
    Partial<Record<CredentialKey, CredentialVerifyStamp>>
  >({});

  const origin = useResolutionOrigin();

  const resolveMaterialDid = useCallback(async () => {
    setDidResolveBusy(true);
    setDidDocError(null);
    const base = resolutionBaseAtRuntime(origin);
    const url = rewriteTabulasHttpsUrl(
      didWebToDidJsonHttpsUrl(MATERIAL_DID),
      base,
    );
    try {
      const res = await fetch(url);
      if (!res.ok) {
        throw new Error(`HTTP ${res.status} for ${url}`);
      }
      const data = await res.json();
      setDidDocJson(JSON.stringify(data, null, 2));
      setDidDocOpen(true);
      setIdentityExpanded(true);
      requestAnimationFrame(() => {
        requestAnimationFrame(() => {
          identitySectionRef.current?.scrollIntoView({
            behavior: "smooth",
            block: "start",
          });
        });
      });
    } catch (e) {
      setDidDocError(
        e instanceof Error ? e.message : "Could not resolve DID document",
      );
    } finally {
      setDidResolveBusy(false);
    }
  }, [origin]);

  const loadCredentialJson = useCallback(async (key: CredentialKey) => {
    if (credentialJson[key]) {
      return;
    }
    const path = CREDENTIAL_PATHS[key];
    const res = await fetch(path);
    const data = await res.json();
    setCredentialJson((prev) => ({
      ...prev,
      [key]: JSON.stringify(data, null, 2),
    }));
  }, [credentialJson]);

  const sleep = (ms: number) =>
    new Promise<void>((r) => {
      setTimeout(r, ms);
    });

  const runVerify = useCallback(
    async (key: CredentialKey) => {
      console.log("[DID demo verify/ui] phase:start", {
        credentialKey: key,
        resolutionOrigin: origin,
        path: CREDENTIAL_PATHS[key],
      });

      setVerifyPanelKey(key);
      setHighlightLine(null);
      setVerifySettled(false);
      setVerifyAnimating(true);
      setFinalVerified(null);
      setVerifyError(null);
      setCredentialVerifyStamp((s) => ({ ...s, [key]: "running" }));

      const path = CREDENTIAL_PATHS[key];
      console.log("[DID demo verify/ui] phase:fetch_vc", { path });
      const res = await fetch(path);
      if (!res.ok) {
        console.error("[DID demo verify/ui] phase:fetch_vc failed", {
          status: res.status,
        });
        setVerifyError(`Could not fetch credential (${res.status})`);
        setFinalVerified(false);
        setVerifySettled(true);
        setVerifyAnimating(false);
        setCredentialVerifyStamp((s) => ({ ...s, [key]: "fail" }));
        return;
      }
      const credential = (await res.json()) as Record<string, unknown>;
      console.log("[DID demo verify/ui] phase:fetch_vc ok", {
        credentialId: credential.id,
        types: credential.type,
      });

      for (let i = 0; i < VERIFY_STEPS.length; i++) {
        console.log("[DID demo verify/ui] phase:ui_animation", {
          stepIndex: i,
          stepLabel: VERIFY_STEPS[i],
        });
        setHighlightLine(i);
        await sleep(220);
      }
      setHighlightLine(null);

      console.log("[DID demo verify/ui] phase:crypto_verify (calling verifyDemoCredential)");
      let outcome: boolean | null = null;
      let errMsg: string | null = null;
      try {
        const result = await verifyDemoCredential(credential, origin);
        outcome = result.verified;
        errMsg = result.error ?? null;
        console.log("[DID demo verify/ui] phase:crypto_verify done", {
          verified: result.verified,
          error: result.error ?? null,
        });
        setFinalVerified(result.verified);
        if (!result.verified && result.error) {
          setVerifyError(result.error);
        }
      } catch (e) {
        console.error("[DID demo verify/ui] phase:crypto_verify threw", e);
        outcome = false;
        errMsg = e instanceof Error ? e.message : "Verification error";
        setFinalVerified(false);
        setVerifyError(errMsg);
      }
      setVerifySettled(true);
      setVerifyAnimating(false);
      setCredentialVerifyStamp((s) => ({
        ...s,
        [key]: outcome === true ? "ok" : "fail",
      }));
      console.log("[DID demo verify/ui] phase:end", {
        credentialKey: key,
        verified: outcome,
        error: errMsg,
      });
    },
    [origin],
  );

  const chainNotes: Record<CredentialKey, string> = {
    product: `This claim describes the material identified as ${MATERIAL_DID}. It is the subject of the environmental declaration and the installation record.`,
    epd: `This environmental declaration applies to the same material (${MATERIAL_DID}). The third-party verification credential attests to this declaration.`,
    verification: `This credential’s subject is the environmental declaration JSON (the EPD credential URL). It chains independent verification to Wienerberger’s EPD.`,
    installation: `This record references the installed product by DID (${MATERIAL_DID}), linking site evidence back to the product and EPD claims.`,
  };

  return (
    <div className="mx-auto max-w-4xl px-4 py-8 sm:px-6 sm:py-10">
      <header className="border-b border-zinc-200 pb-8 dark:border-zinc-800">
        <div className="flex flex-wrap items-center gap-3 border-b border-zinc-100 pb-4 dark:border-zinc-800/80">
          <div className="relative h-9 w-40 shrink-0 sm:h-10 sm:w-44">
            <Image
              src="/images/logo.png"
              alt="Wienerberger"
              fill
              className="object-contain object-left"
              priority
              sizes="176px"
            />
          </div>
          <span className="text-[11px] font-medium uppercase tracking-wide text-zinc-500 sm:ml-auto">
            Manufacturer
          </span>
        </div>

        <div className="mt-4 overflow-hidden rounded-2xl border border-zinc-200 bg-gradient-to-br from-zinc-50 to-white shadow-sm dark:border-zinc-700 dark:from-zinc-900 dark:to-zinc-950 dark:shadow-none">
          <div className="flex flex-col gap-4 p-4 sm:flex-row sm:items-start sm:gap-5 sm:p-5">
            <div className="flex shrink-0 justify-center sm:block sm:pt-0.5">
              <a
                href={EN_15804_CORE_RULES_URL}
                target="_blank"
                rel="noopener noreferrer"
                className="relative block h-24 w-24 overflow-hidden rounded-xl bg-white ring-1 ring-zinc-200 transition-opacity hover:opacity-90 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-zinc-400 dark:bg-zinc-950 dark:ring-zinc-600 dark:focus-visible:ring-zinc-500 sm:h-28 sm:w-28"
                aria-label="UNE EN 15804:2012+A2:2020 — environmental product declarations, core rules for construction products (opens product page in a new tab)"
              >
                <Image
                  src="/images/proto.png"
                  alt=""
                  fill
                  className="object-contain p-1.5"
                  priority
                  sizes="112px"
                />
              </a>
            </div>

            <div className="min-w-0 flex-1">
              <p className="text-[11px] font-semibold uppercase tracking-wide text-zinc-500">
                Tabulas DID + VC demo · product passport
              </p>
              <h1 className="mt-1 text-2xl font-semibold tracking-tight text-zinc-950 sm:text-3xl dark:text-zinc-50">
                One material. Many claims. One identity.
              </h1>
              <p className="mt-2 max-w-xl text-sm leading-snug text-zinc-600 dark:text-zinc-400">
                Porotherm 25 N+F at Residentie De Lindeboom (Bruges, Mar 2026). Four
                signed credentials; cryptographic check is per claim.
              </p>

              <dl className="mt-3 grid grid-cols-1 gap-x-6 gap-y-1.5 text-xs sm:grid-cols-2 sm:text-sm">
                <div className="flex min-w-0 flex-col gap-0.5 sm:flex-row sm:items-baseline sm:gap-2">
                  <dt className="shrink-0 text-zinc-500">Product</dt>
                  <dd className="min-w-0 font-medium text-zinc-900 dark:text-zinc-50">
                    Porotherm 25 N+F
                  </dd>
                </div>
                <div className="flex min-w-0 flex-col gap-0.5 sm:flex-row sm:items-baseline sm:gap-2">
                  <dt className="shrink-0 text-zinc-500">Manufacturer</dt>
                  <dd className="min-w-0 font-medium text-zinc-900 dark:text-zinc-50">
                    Wienerberger EOOD
                  </dd>
                </div>
                <div className="flex min-w-0 flex-col gap-0.5 sm:flex-row sm:items-baseline sm:gap-2">
                  <dt className="shrink-0 text-zinc-500">Site record</dt>
                  <dd className="min-w-0 text-zinc-800 dark:text-zinc-200">
                    Bouwwerken Vandevelde · Sint-Andries
                  </dd>
                </div>
                <div className="flex min-w-0 flex-col gap-0.5 sm:flex-row sm:items-baseline sm:gap-2">
                  <dt className="shrink-0 text-zinc-500">Scope</dt>
                  <dd className="min-w-0 text-zinc-800 dark:text-zinc-200">
                    Demo EPD chain (not an official registry entry)
                  </dd>
                </div>
              </dl>

              <div className="mt-4 border-t border-zinc-200/90 pt-3 dark:border-zinc-700/80">
                <p className="text-[11px] font-semibold uppercase tracking-wide text-zinc-500">
                  Credential signatures
                </p>
                <p className="mt-0.5 text-[11px] leading-snug text-zinc-500 dark:text-zinc-400">
                  ○ not checked yet · ✓ proof OK · ✗ proof failed — tap to run the same
                  Verify as in the table (one at a time).
                </p>
                <div className="mt-2 flex flex-wrap gap-2">
                  {CARDS.map((c) => {
                    const stamp = credentialVerifyStamp[c.key];
                    return (
                      <button
                        key={c.key}
                        type="button"
                        title={`Verify ${c.title}`}
                        disabled={verifyAnimating}
                        onClick={() => void runVerify(c.key)}
                        className={`${verifyStampChipClass(stamp)} disabled:cursor-not-allowed disabled:opacity-50`}
                      >
                        <span className="text-[11px] font-semibold leading-tight">
                          {PASSPORT_CLAIM_LABEL[c.key]}
                        </span>
                        <span className="mt-0.5 flex items-center gap-1 text-[10px] font-medium opacity-90">
                          <span className="w-3 shrink-0 text-center" aria-hidden>
                            {verifyStampGlyph(stamp)}
                          </span>
                          {verifyStampLabel(stamp)}
                        </span>
                      </button>
                    );
                  })}
                </div>
              </div>

              <div className="mt-4 flex flex-col gap-2 border-t border-zinc-200/90 pt-3 sm:flex-row sm:items-center sm:gap-3 dark:border-zinc-700/80">
                <code className="min-w-0 flex-1 break-all rounded-md bg-zinc-100 px-2 py-1.5 text-[11px] leading-snug text-zinc-800 dark:bg-zinc-900 dark:text-zinc-200 sm:text-xs">
                  {MATERIAL_DID}
                </code>
                <button
                  type="button"
                  onClick={() => void resolveMaterialDid()}
                  disabled={didResolveBusy}
                  className="inline-flex shrink-0 items-center justify-center rounded-md bg-zinc-900 px-3 py-2 text-xs font-medium text-white hover:bg-zinc-800 disabled:opacity-60 dark:bg-zinc-100 dark:text-zinc-900 dark:hover:bg-zinc-200 sm:text-sm"
                >
                  {didResolveBusy ? "Resolving…" : "Resolve DID"}
                </button>
              </div>
              <p className="mt-1.5 text-[11px] leading-snug text-zinc-500 dark:text-zinc-400">
                Loads <code className="text-zinc-700 dark:text-zinc-300">did.json</code> for this{" "}
                <span className="font-medium">did:web</span> id (same host as this page) and opens it under{" "}
                <span className="font-medium text-zinc-600 dark:text-zinc-300">Its identity</span>.
              </p>
              {didDocError ? (
                <p className="mt-2 text-sm text-red-600" role="alert">
                  {didDocError}
                </p>
              ) : null}
            </div>
          </div>
        </div>
      </header>

      <section className="mt-6" aria-labelledby="claims-heading">
        <h2
          id="claims-heading"
          className="text-xl font-semibold text-zinc-900 dark:text-zinc-50"
        >
          The claims
        </h2>
        <p className="mt-1 max-w-2xl text-sm text-zinc-500 dark:text-zinc-400">
          Expand a row for the issuer line, then <span className="font-medium text-zinc-700 dark:text-zinc-300">Verify</span>{" "}
          or use the passport chips above. The pipeline below follows the active claim.
        </p>

        <div className="mt-4 overflow-x-auto rounded-lg border border-zinc-200 bg-white dark:border-zinc-800 dark:bg-zinc-950">
          <table className="w-full min-w-[760px] border-collapse text-left text-sm">
            <thead>
              <tr className="border-b border-zinc-200 bg-zinc-50 text-xs font-semibold uppercase tracking-wide text-zinc-600 dark:border-zinc-800 dark:bg-zinc-900/80 dark:text-zinc-400">
                <th className="px-3 py-3 align-bottom">Claim</th>
                <th className="px-3 py-3 align-bottom">Issuer</th>
                <th className="px-3 py-3 align-bottom">Summary</th>
                <th className="whitespace-nowrap px-3 py-3 align-bottom">
                  Valid from
                </th>
                <th
                  className="w-14 whitespace-nowrap px-2 py-3 text-center align-bottom"
                  title="Last cryptographic verification on this device"
                >
                  Check
                </th>
                <th className="px-3 py-3 align-bottom">Actions</th>
              </tr>
            </thead>
            <tbody>
              {CARDS.map((c) => {
                const narrative = Boolean(claimNarrativeOpen[c.key]);
                const jsonOpen = Boolean(claimJsonOpen[c.key]);
                return (
                  <Fragment key={c.key}>
                    <tr className="border-b border-zinc-100 align-top dark:border-zinc-800/90">
                      <td className="px-3 py-3">
                        <button
                          type="button"
                          className="flex max-w-[14rem] items-start gap-2 rounded-md text-left text-base font-semibold text-zinc-900 outline-none ring-zinc-400 hover:bg-zinc-50 focus-visible:ring-2 dark:text-zinc-50 dark:hover:bg-zinc-900/60 dark:ring-zinc-500"
                          aria-expanded={narrative}
                          onClick={() =>
                            setClaimNarrativeOpen((prev) => ({
                              ...prev,
                              [c.key]: !prev[c.key],
                            }))
                          }
                        >
                          <span className="mt-0.5 shrink-0 text-zinc-400" aria-hidden>
                            {narrative ? "▼" : "▶"}
                          </span>
                          <span>{c.title}</span>
                        </button>
                      </td>
                      {narrative ? (
                        <>
                          <td className="px-3 py-3 text-zinc-600 dark:text-zinc-400">
                            {c.issuerLine}
                          </td>
                          <td className="px-3 py-3 italic text-zinc-700 dark:text-zinc-300">
                            &ldquo;{c.quote}&rdquo;
                          </td>
                          <td className="whitespace-nowrap px-3 py-3 text-xs text-zinc-500 dark:text-zinc-400">
                            {c.dateLabel}
                          </td>
                        </>
                      ) : (
                        <td
                          colSpan={3}
                          className="px-3 py-3 text-zinc-400 dark:text-zinc-500"
                        >
                          <span className="italic">Collapsed — expand the claim</span>
                        </td>
                      )}
                      <td
                        className="px-2 py-3 text-center align-middle text-base tabular-nums leading-none text-zinc-700 dark:text-zinc-200"
                        title={verifyStampLabel(credentialVerifyStamp[c.key])}
                      >
                        <span aria-hidden>{verifyStampGlyph(credentialVerifyStamp[c.key])}</span>
                        <span className="sr-only">{verifyStampLabel(credentialVerifyStamp[c.key])}</span>
                      </td>
                      <td className="px-3 py-3">
                        <div className="flex flex-col gap-2 sm:flex-row sm:flex-wrap">
                          <button
                            type="button"
                            disabled={verifyAnimating}
                            className="inline-flex justify-center rounded-md bg-emerald-700 px-3 py-2 text-xs font-medium text-white hover:bg-emerald-800 disabled:pointer-events-none disabled:opacity-50 sm:text-sm"
                            onClick={() => void runVerify(c.key)}
                          >
                            Verify
                          </button>
                          <button
                            type="button"
                            className="inline-flex justify-center rounded-md border border-zinc-300 bg-white px-3 py-2 text-xs font-medium text-zinc-800 hover:bg-zinc-50 dark:border-zinc-600 dark:bg-zinc-900 dark:text-zinc-200 dark:hover:bg-zinc-800 sm:text-sm"
                            aria-expanded={jsonOpen}
                            onClick={() => {
                              const willOpen = !claimJsonOpen[c.key];
                              setClaimJsonOpen((prev) => ({
                                ...prev,
                                [c.key]: !prev[c.key],
                              }));
                              if (willOpen && !credentialJson[c.key]) {
                                void loadCredentialJson(c.key);
                              }
                            }}
                          >
                            {jsonOpen ? "Hide details" : "Show details"}
                          </button>
                        </div>
                      </td>
                    </tr>
                    {jsonOpen ? (
                      <tr className="border-b border-zinc-100 bg-zinc-50/80 dark:border-zinc-800 dark:bg-zinc-900/40">
                        <td colSpan={6} className="px-3 py-3">
                          {credentialJson[c.key] ? (
                            <pre
                              className="max-h-72 overflow-auto rounded-md border border-zinc-200 bg-white p-3 text-xs leading-relaxed text-zinc-800 dark:border-zinc-700 dark:bg-zinc-950 dark:text-zinc-200"
                              tabIndex={0}
                            >
                              {credentialJson[c.key]}
                            </pre>
                          ) : (
                            <p className="text-xs text-zinc-500">Loading…</p>
                          )}
                        </td>
                      </tr>
                    ) : null}
                  </Fragment>
                );
              })}
            </tbody>
          </table>
        </div>

        <div
          className="mt-6 rounded-xl border border-zinc-200 bg-zinc-50 p-5 dark:border-zinc-800 dark:bg-zinc-900/50"
          aria-live="polite"
          aria-labelledby="verify-panel-title"
        >
          <h3
            id="verify-panel-title"
            className="text-sm font-semibold uppercase tracking-wide text-zinc-600 dark:text-zinc-400"
          >
            Verification pipeline
          </h3>
          {!verifyPanelKey ? (
            <p className="mt-2 text-sm text-zinc-600 dark:text-zinc-300">
              Click <span className="font-medium text-zinc-800 dark:text-zinc-200">Verify</span>{" "}
              on a claim row to run the five checks here — without leaving this
              section.
            </p>
          ) : (
            <>
              <p className="mt-1 text-xs text-zinc-500 dark:text-zinc-400">
                Active credential:{" "}
                <span className="font-medium text-zinc-800 dark:text-zinc-200">
                  {CARDS.find((x) => x.key === verifyPanelKey)?.title}
                </span>
              </p>
              <div className="mt-4 flex flex-wrap gap-2" aria-hidden>
                {VERIFY_STEPS.map((label, i) => {
                  const isLast = i === VERIFY_STEPS.length - 1;
                  const past = highlightLine !== null && i < highlightLine;
                  const active = highlightLine === i;
                  const cryptoWait =
                    isLast &&
                    highlightLine === null &&
                    !verifySettled &&
                    verifyAnimating;
                  let tone =
                    "border-zinc-200 bg-white text-zinc-500 dark:border-zinc-700 dark:bg-zinc-950 dark:text-zinc-400";
                  if (verifySettled && finalVerified === true) {
                    tone =
                      "border-emerald-300 bg-emerald-50 text-emerald-900 dark:border-emerald-700 dark:bg-emerald-950/50 dark:text-emerald-100";
                  } else if (verifySettled && finalVerified === false && isLast) {
                    tone =
                      "border-red-300 bg-red-50 text-red-900 dark:border-red-800 dark:bg-red-950/40 dark:text-red-100";
                  } else if (past || (verifySettled && finalVerified === true)) {
                    tone =
                      "border-emerald-200 bg-emerald-50/80 text-emerald-900 dark:border-emerald-800 dark:bg-emerald-950/30 dark:text-emerald-100";
                  } else if (active || cryptoWait) {
                    tone =
                      "border-zinc-400 bg-zinc-100 text-zinc-900 ring-2 ring-zinc-300 dark:border-zinc-500 dark:bg-zinc-800 dark:text-zinc-50 dark:ring-zinc-600";
                  }
                  return (
                    <span
                      key={label}
                      className={`inline-flex max-w-[11rem] flex-col rounded-md border px-2 py-1.5 text-[11px] font-medium leading-tight sm:max-w-none sm:text-xs ${tone}`}
                    >
                      <span className="text-[10px] uppercase tracking-wide opacity-80">
                        Step {i + 1}
                      </span>
                      <span className="mt-0.5">{label}</span>
                    </span>
                  );
                })}
              </div>
              <ol className="mt-4 space-y-2 border-t border-zinc-200 pt-4 dark:border-zinc-700/80">
                {VERIFY_STEPS.map((label, i) => {
                  const isLast = i === VERIFY_STEPS.length - 1;
                  const past = highlightLine !== null && i < highlightLine;
                  const active = highlightLine === i;
                  const cryptoWait =
                    isLast &&
                    highlightLine === null &&
                    !verifySettled &&
                    verifyAnimating;

                  let icon: ReactNode = null;
                  if (verifySettled) {
                    if (finalVerified === true) {
                      icon = <span className="text-emerald-600">✓</span>;
                    } else if (finalVerified === false && isLast) {
                      icon = <span className="text-red-600">✗</span>;
                    }
                  } else if (past) {
                    icon = <span className="text-emerald-600">✓</span>;
                  } else if (active || cryptoWait) {
                    icon = <span className="text-zinc-400">…</span>;
                  }

                  return (
                    <li
                      key={label}
                      className={`flex items-center gap-3 text-sm ${
                        active || cryptoWait
                          ? "font-medium text-zinc-900 dark:text-zinc-100"
                          : "text-zinc-600 dark:text-zinc-400"
                      }`}
                    >
                      <span className="w-6 shrink-0 text-center" aria-hidden>
                        {icon}
                      </span>
                      <span>{label}</span>
                    </li>
                  );
                })}
              </ol>
              {verifySettled && finalVerified === false ? (
                <p className="mt-4 text-sm font-medium text-red-600" role="alert">
                  This signature does not match the claim.
                  {verifyError ? ` (${verifyError})` : ""}
                </p>
              ) : null}
              {verifySettled && finalVerified === true ? (
                <div className="mt-4 text-sm leading-relaxed text-zinc-700 dark:text-zinc-300">
                  <p className="font-medium text-emerald-800 dark:text-emerald-400">
                    Signature verified.
                  </p>
                  <p className="mt-2">{chainNotes[verifyPanelKey]}</p>
                  <ul className="mt-2 list-disc space-y-1 pl-5">
                    <li>
                      <a
                        className="text-zinc-900 underline dark:text-zinc-100"
                        href={rewriteTabulasHttpsUrl(
                          "https://tabulas.eu/credentials/wienerberger/porotherm-25-nf/product-declaration.json",
                          origin,
                        )}
                      >
                        Product declaration JSON
                      </a>
                    </li>
                    <li>
                      <a
                        className="text-zinc-900 underline dark:text-zinc-100"
                        href={rewriteTabulasHttpsUrl(
                          "https://tabulas.eu/credentials/wienerberger/porotherm-25-nf/epd.json",
                          origin,
                        )}
                      >
                        Environmental declaration JSON
                      </a>
                    </li>
                    <li>
                      <a
                        className="text-zinc-900 underline dark:text-zinc-100"
                        href={rewriteTabulasHttpsUrl(
                          "https://tabulas.eu/credentials/wienerberger/porotherm-25-nf/verification.json",
                          origin,
                        )}
                      >
                        Third-party verification JSON
                      </a>
                    </li>
                    <li>
                      <a
                        className="text-zinc-900 underline dark:text-zinc-100"
                        href={rewriteTabulasHttpsUrl(
                          "https://tabulas.eu/credentials/bouwwerken-vandevelde/sint-andries-2026/porotherm-25-nf-batch-001.json",
                          origin,
                        )}
                      >
                        Installation record JSON
                      </a>
                    </li>
                  </ul>
                </div>
              ) : null}
            </>
          )}
        </div>
      </section>

      <div className="mt-8">
        <DisclosureCallout
          id="disclosure-top"
          expanded={disclosureTopOpen}
          onToggle={() => setDisclosureTopOpen((v) => !v)}
        />
      </div>

      <section className="mt-14" aria-labelledby="element-heading">
        <button
          type="button"
          id="element-heading"
          className="flex w-full items-start justify-between gap-3 rounded-lg text-left outline-none ring-zinc-400 focus-visible:ring-2 dark:ring-zinc-500"
          aria-expanded={elementExpanded}
          onClick={() => setElementExpanded((v) => !v)}
        >
          <h2 className="text-xl font-semibold text-zinc-900 dark:text-zinc-50">
            The element
          </h2>
          <span
            className="mt-1 shrink-0 text-zinc-400 tabular-nums"
            aria-hidden
          >
            {elementExpanded ? "▼" : "▶"}
          </span>
        </button>
        {elementExpanded ? (
          <div className="mt-4 space-y-4 text-base leading-relaxed text-zinc-700 dark:text-zinc-300">
            <p>
              This is a load-bearing clay masonry block. 25 centimetres thick,
              tongue-and-groove edges, compressive strength of 10 megapascals.
              Wienerberger has manufactured this block at their factory in
              Lukovit, Bulgaria, since 2007. In March 2026, 2,400 kilograms of
              these blocks were installed in the east wing of Residentie De
              Lindeboom, a twelve-unit apartment building in Sint-Andries,
              Bruges.
            </p>
            <p>
              All of that information already exists. What didn&apos;t exist,
              until now, was a single identifier that ties it together — and
              stays attached for the next 50 years.
            </p>
          </div>
        ) : null}
      </section>

      <section
        ref={identitySectionRef}
        className="mt-14 scroll-mt-6"
        aria-labelledby="identity-heading"
      >
        <button
          type="button"
          id="identity-heading"
          className="flex w-full items-start justify-between gap-3 rounded-lg text-left outline-none ring-zinc-400 focus-visible:ring-2 dark:ring-zinc-500"
          aria-expanded={identityExpanded}
          onClick={() => setIdentityExpanded((v) => !v)}
        >
          <h2 className="text-xl font-semibold text-zinc-900 dark:text-zinc-50">
            Its identity
          </h2>
          <span
            className="mt-1 shrink-0 text-zinc-400 tabular-nums"
            aria-hidden
          >
            {identityExpanded ? "▼" : "▶"}
          </span>
        </button>
        {identityExpanded ? (
          <div className="mt-4">
            <p className="text-base leading-relaxed text-zinc-700 dark:text-zinc-300">
              Every Porotherm block produced under this EPD shares one identity.
              That identity is a string: a Decentralized Identifier, or DID. It
              looks like a URL, but it&apos;s not owned by a platform. Anyone,
              anywhere, can resolve it to find out what this material is — and
              who&apos;s said what about it.
            </p>
            <p className="mt-2 text-base leading-relaxed text-zinc-700 dark:text-zinc-300">
              This identifier resolves anywhere in the world. No platform owns
              it.
            </p>
            <button
              type="button"
              className="mt-4 text-sm font-medium text-zinc-900 underline decoration-zinc-400 underline-offset-4 hover:decoration-zinc-600 dark:text-zinc-100"
              aria-expanded={didDocOpen}
              onClick={() => {
                setDidDocOpen((o) => !o);
                if (!didDocJson && !didDocOpen) {
                  void resolveMaterialDid();
                }
              }}
            >
              {didDocOpen ? "Hide identity document" : "Show identity document"}
            </button>
            {didDocOpen && didDocJson ? (
              <pre
                className="mt-4 max-h-96 overflow-auto rounded-lg border border-zinc-200 bg-zinc-50 p-4 text-xs leading-relaxed text-zinc-800 dark:border-zinc-700 dark:bg-zinc-950 dark:text-zinc-200"
                tabIndex={0}
              >
                {didDocJson}
              </pre>
            ) : null}
          </div>
        ) : null}
      </section>


      <details className="mt-16 group/why rounded-lg px-5 py-4 ring-zinc-200 open:ring-2 open:ring-zinc-300 dark:ring-zinc-700 dark:open:ring-zinc-600 sm:px-9 sm:py-6">
        <summary
          id="why-heading"
          className="flex cursor-pointer list-none items-start justify-between gap-3 rounded-lg py-2 outline-none marker:content-none [&::-webkit-details-marker]:hidden focus-visible:ring-2 focus-visible:ring-zinc-400 sm:py-3 dark:focus-visible:ring-zinc-500"
        >
          <h2 className="text-xl font-semibold text-zinc-900 dark:text-zinc-50">
            Why this matters
          </h2>
          <span
            className="mt-1 shrink-0 text-zinc-500 transition-transform group-open/why:rotate-90 dark:text-zinc-400"
            aria-hidden
          >
            ▶
          </span>
        </summary>
        <div className="mt-5 space-y-6 border-t border-zinc-200 pt-8 text-base leading-relaxed text-zinc-700 dark:border-zinc-800 dark:text-zinc-300 sm:mt-6 sm:space-y-8 sm:pt-10">
          <div className="border-b border-zinc-200 pb-6 dark:border-zinc-700/80 sm:pb-8">
            <p className="max-w-prose">{WHY_SIGNED_CLAIM_INTRO}</p>
          </div>
          <div>
            <h3 className="font-semibold text-zinc-900 dark:text-zinc-50">
              Your signature stays on your data.
            </h3>
            <p className="mt-2">
              Wienerberger&apos;s environmental declaration is no longer a PDF
              in someone else&apos;s database. It is a signed claim, with
              Wienerberger&apos;s name on it, that anyone can verify against
              Wienerberger&apos;s public key. The data cannot be edited without
              breaking the signature.
            </p>
          </div>
          <div>
            <h3 className="font-semibold text-zinc-900 dark:text-zinc-50">
              The verifier stays attached.
            </h3>
            <p className="mt-2">
              Dr. Minkov of greentability verified this EPD on June 17, 2025.
              That verification is itself a signed claim, attached to
              Wienerberger&apos;s declaration. Fifty years from now, when this
              building is renovated, the new owner will still be able to prove
              that this material was independently verified — and by whom.
            </p>
          </div>
          <div>
            <h3 className="font-semibold text-zinc-900 dark:text-zinc-50">
              The platform is replaceable. The trust is not.
            </h3>
            <p className="mt-2">
              If Tabulas disappears tomorrow, these claims still verify. The
              cryptography does not depend on us being online. That is what
              separates digital identity from a database entry.
            </p>
          </div>
        </div>
      </details>

      <section className="mt-14 border-t border-zinc-200 pt-10 dark:border-zinc-800">
        <h2 className="text-lg font-semibold text-zinc-900 dark:text-zinc-50">
          What&apos;s next
        </h2>
        <p className="mt-3 text-base text-zinc-700 dark:text-zinc-300">
          Tabulas v2 anchors these identities to IOTA, removing the last
          dependency on any single platform. Coming summer 2026.{" "}
          <a
            href="mailto:hello@tabulas.eu?subject=DID%20demo"
            className="font-medium text-zinc-900 underline dark:text-zinc-100"
          >
            Talk to us
          </a>
        </p>
      </section>

      <footer className="mt-16 border-t border-zinc-200 pt-10 dark:border-zinc-800">
        <DisclosureCallout
          id="disclosure-footer"
          expanded={disclosureFooterOpen}
          onToggle={() => setDisclosureFooterOpen((v) => !v)}
        />
        <nav
          className="mt-8 flex flex-wrap gap-x-6 gap-y-2 text-sm"
          aria-label="References"
        >
          <a
            className="text-zinc-700 underline dark:text-zinc-300"
            href="https://www.w3.org/TR/did-core/"
          >
            W3C DID Core
          </a>
          <a
            className="text-zinc-700 underline dark:text-zinc-300"
            href="https://www.w3.org/TR/vc-data-model-2.0/"
          >
            W3C Verifiable Credentials 2.0
          </a>
          <a
            className="text-zinc-700 underline dark:text-zinc-300"
            href={EN_15804_CORE_RULES_URL}
          >
            EN 15804
          </a>
        </nav>
        <p className="mt-6 text-sm text-zinc-500">
          Tabulas —{" "}
          <a className="underline" href="https://tabulas.eu">
            tabulas.eu
          </a>
        </p>
      </footer>
    </div>
  );
}
